changelog:
  exclude:
    labels:
      - 🧠 Meta
      - 🕰️ Past Dependencies

  categories:
    - title: 🐙 GitHub Actions
      labels: [🐙 GitHub Actions]
    - title: 🏷️ Label Past Pull Requests
      labels: [🏷️ Label Past Pull Requests]
    - title: 🚸 pre-commit
      labels: [🚸 pre-commit]
    - title: 🍞 Setup Bun with Cache
      labels: [🍞 Setup Bun with Cache]
    - title: 🏷️ Labeler
      labels: [🏷️ Labeler]
    - title: 🎨 Renovate
      labels: [🎨 Renovate]
