changelog:
  categories:
    - title: 🐙 GitHub Actions
      labels: [🐙 GitHub Actions]
    - title: 🏷️ Label Past Pull Requests
      labels: [🏷️ Label Past Pull Requests]
    - title: 🚸 pre-commit
      labels: [🚸 pre-commit]
    - title: 🍞 Setup Bun with Cache
      labels: [🍞 Setup Bun with Cache]
    - title: 🔒 Update Deno Lock File
      labels: [🔒 Update Deno Lock File]
    - title: 🏷️ Labeler
      labels: [🏷️ Labeler]
    - title: 🎨 Renovate
      labels: [🎨 Renovate]
