- id: upload-git-commit-notion
  name: Upload Git Commits to Notion
  description: Upload not pushed Git commits data to Notion database
  entry: pre-commit/scripts/upload-git-commit-notion
  language: unsupported_script
  always_run: true
  verbose: true
  pass_filenames: false
  stages: [pre-push]
