- id: upload-git-commit-notion
  name: Upload Git Commits to Notion
  description: Upload not pushed Git commits data to Notion database
  entry: pre-commit/hooks/upload-git-commit-notion/main.ts
  language: deno
  always_run: true
  verbose: true
  pass_filenames: false
  stages: [pre-push]
