name: 🦕 Setup Deno with Cache
description: Install Deno and cache project dependencies

runs:
  using: composite

  steps:
    - name: 🦕 Setup Deno
      uses: denoland/setup-deno@909cc5acb0fdd60627fb858598759246509fa755 # v2.0.2

    - name: 🫙 Cache Deno Dependencies
      uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4.2.1
      with:
        path: |
          ~/.deno
          ~/.cache/deno
        key: ${{ runner.os }}-deno-${{ hashFiles('./deno.lock') }}
