name: 🦕 Setup Deno with Cache
description: Install Deno and cache project dependencies

runs:
  using: composite

  steps:
    - name: 🦕 Setup Deno
      uses: denoland/setup-deno@909cc5acb0fdd60627fb858598759246509fa755 # v2.0.2

    - name: 🫙 Cache Deno Dependencies
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: |
          ~/.deno
          ~/.cache/deno
        key: ${{ runner.os }}-deno-${{ hashFiles('./deno.lock') }}
