name: 🦕 Setup Deno with Cache
description: Install Deno and cache project dependencies

runs:
  using: composite

  steps:
    - name: 🦕 Setup Deno
      uses: denoland/setup-deno@909cc5acb0fdd60627fb858598759246509fa755 # v2.0.2

    - name: 🫙 Cache Deno Dependencies
      uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
      with:
        path: |
          ~/.deno
          ~/.cache/deno
        key: ${{ runner.os }}-deno-${{ hashFiles('./deno.lock') }}
