name: 🦕 Setup Deno with Cache
description: Install Deno and cache project dependencies

runs:
  using: composite

  steps:
    - name: 🦕 Setup Deno
      uses: denoland/setup-deno@909cc5acb0fdd60627fb858598759246509fa755 # v2.0.2

    - name: 🫙 Cache Deno Dependencies
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: |
          ~/.deno
          ~/.cache/deno
        key: ${{ runner.os }}-deno-${{ hashFiles('./deno.lock') }}
