name: 🚸 pre-commit
description: Check the code with pre-commit hooks

runs:
  using: composite

  steps:
    - name: 🚚 Checkout Repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: 🐍 Setup Python
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0

    - name: 🚸 Install pre-commit
      run: pip install pre-commit
      shell: bash

    - name: "#️⃣ Download pre-commit hooks"
      if: ${{ hashFiles('./.pre-commit-config.yaml') == '' }}
      run: curl -O "https://raw.githubusercontent.com/5ouma/utils/refs/heads/main/.pre-commit-config.yaml"
      shell: bash

    - name: 🫙 Cache pre-commit Dependencies
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('./.pre-commit-config.yaml') }}

    - name: 🚸 Run pre-commit
      run: pre-commit run -a
      shell: bash

    - name: 🚸 Run pre-commit-ci-lite
      if: ${{ always() }}
      uses: pre-commit-ci/lite-action@5d6cc0eb514c891a40562a58a8e71576c5c7fb43 # v1.1.0
      with:
        msg: "chore(fix): Auto fixes by pre-commit hooks"
