name: 🚸 pre-commit
description: Check the code with pre-commit hooks

runs:
  using: composite

  steps:
    - name: 🚚 Checkout Repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false

    - name: 🐍 Setup Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0

    - name: 🚸 Install pre-commit
      run: pip install pre-commit
      shell: bash

    - name: "#️⃣ Download pre-commit hooks"
      if: ${{ hashFiles('./.pre-commit-config.yaml') == '' }}
      run: curl -O "https://raw.githubusercontent.com/5ouma/utils/$ACTION_REF/.pre-commit-config.yaml"
      shell: bash
      env:
        ACTION_REF: ${{ github.action_ref }}

    - name: 🫙 Cache pre-commit Dependencies
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('./.pre-commit-config.yaml') }}

    - name: 🚸 Run pre-commit
      run: pre-commit run -a
      shell: bash

    - name: 🚸 Run pre-commit-ci-lite
      if: ${{ always() }}
      uses: pre-commit-ci/lite-action@5d6cc0eb514c891a40562a58a8e71576c5c7fb43 # v1.1.0
      with:
        msg: "chore(fix): Auto fixes by pre-commit hooks"
