name: 🚸 pre-commit
description: Check the code with pre-commit hooks

inputs:
  token:
    description: GitHub token
    required: false

runs:
  using: composite

  steps:
    - name: 🚚 Check out repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false

    - name: ⚡ Install prek
      run: curl -L "https://github.com/j178/prek/releases/download/$PREK_VERSION/prek-installer.sh" | sh
      shell: bash
      env:
        PREK_VERSION: v0.2.1

    - name: "#️⃣ Download pre-commit hooks"
      id: hooks
      if: ${{ hashFiles('./.pre-commit-config.yaml') == '' }}
      run: |
        curl -O "https://raw.githubusercontent.com/$ACTION_REPOSITORY/$ACTION_REF/.pre-commit-config.yaml"
        echo 'downloaded=true' | tee -a "$GITHUB_OUTPUT"
      shell: bash
      env:
        ACTION_REPOSITORY: ${{ github.action_repository }}
        ACTION_REF: ${{ github.action_ref }}

    - name: 🫙 Cache pre-commit dependencies
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        path: ~/.cache/prek
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('./.pre-commit-config.yaml') }}
        restore-keys: ${{ runner.os }}-pre-commit-

    - name: ⚡ Run prek
      run: prek run -a
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: 🗑️ Remove downloaded hooks
      if: ${{ always() && steps.hooks.outputs.downloaded == 'true' }}
      run: rm .pre-commit-config.yaml
      shell: bash

    - name: 🚸 Run pre-commit-ci-lite
      if: ${{ always() }}
      uses: pre-commit-ci/lite-action@5d6cc0eb514c891a40562a58a8e71576c5c7fb43 # v1.1.0
      with:
        msg: "chore(fix): Auto fixes by pre-commit hooks"
