name: 🚸 pre-commit
description: Check the code with pre-commit hooks

inputs:
  config:
    description: pre-commit config file path
    required: false
    default: .pre-commit-config.yaml
  token:
    description: GitHub token
    required: false

runs:
  using: composite

  steps:
    - name: 🚚 Check out repository
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      with:
        persist-credentials: false

    - name: ⚡ Install prek
      run: curl -L "https://github.com/j178/prek/releases/download/$PREK_VERSION/prek-installer.sh" | sh
      shell: bash
      env:
        PREK_VERSION: v0.2.18

    - name: "#️⃣ Download pre-commit hooks"
      id: hooks
      if: ${{ hashFiles(inputs.config) == '' }}
      run: |
        curl -O "https://raw.githubusercontent.com/$ACTION_REPOSITORY/$ACTION_REF/.pre-commit-config.yaml"
        echo 'downloaded=true' | tee -a "$GITHUB_OUTPUT"
      shell: bash
      env:
        ACTION_REPOSITORY: ${{ github.action_repository }}
        ACTION_REF: ${{ github.action_ref }}

    - name: 🫙 Cache pre-commit dependencies
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ~/.cache/prek
        key: ${{ runner.os }}-pre-commit-${{ hashFiles(inputs.config) }}
        restore-keys: ${{ runner.os }}-pre-commit-

    - name: ⚡ Run prek
      run: prek run -ac="$PREK_CONFIG"
      shell: bash
      env:
        PREK_CONFIG: ${{ inputs.config }}
        GH_TOKEN: ${{ inputs.token }}
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: 🗑️ Remove downloaded hooks
      if: ${{ always() && steps.hooks.outputs.downloaded == 'true' }}
      run: rm "$PREK_CONFIG"
      shell: bash
      env:
        PREK_CONFIG: ${{ inputs.config }}

    - name: 🚸 Run pre-commit-ci-lite
      if: ${{ always() }}
      uses: pre-commit-ci/lite-action@5d6cc0eb514c891a40562a58a8e71576c5c7fb43 # v1.1.0
      with:
        msg: "chore(fix): Auto fixes by pre-commit hooks"
