#!/usr/bin/env bash

set -euo pipefail

commands=(op jq)
for cmd in "${commands[@]}"; do
  (type "$cmd" &>/dev/null) || exit 0
done

itemData="$(op item get 'Notion Git Integration' --fields='label=database-id,credential' --reveal)" && declare -r itemData
databaseId="$(echo "$itemData" | cut -d ',' -f 1)" && declare -r databaseId
credential="$(echo "$itemData" | cut -d ',' -f 2)" && declare -r credential

url="https://$(git config --get remote.origin.url | sed -Ee 's/((https|ssh):\/\/|git@|\.git)//g' -e 's/:/\//')" && declare -r url
declare message description date notionData
while read -r hash; do
  message="$(git log -n 1 "$hash" --format='%s')"
  description="$(git log -n 1 "$hash" --format='%b')"
  date="$(git log -n 1 "$hash" --format='%ad' --date=format:'%Y-%m-%d %H:%M:%S')"

  notionData="$(
    cat <<EOF
{
  "parent": { "database_id": "$databaseId" },
  "properties": {
    "Message": { "title": [{ "text": { "content": "$message" } }] },
    "Description": { "rich_text": [{ "text": { "content": "$description" } }] },
    "Hash": { "rich_text": [{ "text": { "content": "$hash" } }] },
    "URL": { "url": "$url" },
    "Date": { "date": { "start": "$date", "time_zone": "Asia/Tokyo" } }
  }
}
EOF
  )"

  curl -s -X POST https://api.notion.com/v1/pages \
    -H "Authorization: Bearer $credential" \
    -H 'Content-Type: application/json' \
    -H 'Notion-Version: 2025-09-03' \
    --data "$notionData" |
    jq -r '.id'
done < <(git log --branches --not --remotes --format='%h')
