name: 🍞 Setup Bun with Cache
description: Install Bun and cache project dependencies

runs:
  using: composite

  steps:
    - name: 🍞 Set up Bun
      uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2

    - name: 🫙 Cache node_modules
      id: cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ./node_modules
        key: ${{ runner.os }}-bun-${{ hashFiles('./bun.lock') }}

    - name: 📦 Install dependencies
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      run: bun install --frozen-lockfile
      shell: bash
