name: 🍞 Setup Bun with Cache
description: Install Bun and cache project dependencies

runs:
  using: composite

  steps:
    - name: 🍞 Setup Bun
      uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2

    - name: 🫙 Cache node_modules
      id: cache
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ./node_modules
        key: ${{ runner.os }}-bun-${{ hashFiles('./bun.lock', './bun.lockb') }}

    - name: 📦 Install Dependencies
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      run: bun install --frozen-lockfile
      shell: bash
