name: 🍞 Setup Bun with Cache
description: Install Bun and cache project dependencies

runs:
  using: composite

  steps:
    - name: 🍞 Set up Bun
      uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0

    - name: 🫙 Cache node_modules
      id: cache
      uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        path: ./node_modules
        key: bun-${{ runner.os }}-${{ hashFiles('./bun.lock') }}

    - name: 📦 Install dependencies
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      run: bun install --frozen-lockfile
      shell: bash
