name: 🍞 Setup Bun with Cache
description: Install Bun and cache project dependencies

runs:
  using: composite

  steps:
    - name: 🍞 Setup Bun
      uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2.0.1

    - name: 🫙 Cache node_modules
      id: cache
      uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
      with:
        path: ./node_modules
        key: ${{ runner.os }}-bun-${{ hashFiles('./bun.lock', './bun.lockb') }}

    - name: 📦 Install Dependencies
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      run: bun install --frozen-lockfile
      shell: bash
