name: 🔒 Update Deno Lock File
description: Post update action for deno.lock

inputs:
  directory:
    description: Path to the source directory
    required: false
    default: src

outputs:
  file_changed:
    description: If any files are modified
    value: ${{ steps.check.outputs.files != '' }}

runs:
  using: composite

  steps:
    - name: 🦕 Setup Deno
      uses: 5ouma/utils/setup-deno-with-cache@f5466cbecd9bcaa9d35e14ece162ca78122406d3 # v0.1.5

    - name: 🔒 Update Lock File
      env:
        DIRECTORY: ${{ inputs.directory }}
      run: deno cache "$DIRECTORY" --frozen=false
      shell: bash

    - name: 🔍 Check Changes
      id: check
      run: echo "files=$(git ls-files -mo --exclude-standard)" | tee -a "$GITHUB_OUTPUT"
      shell: bash

    - name: 📝 Commit and Push Changes
      if: ${{ steps.check.outputs.files != '' }}
      uses: suzuki-shunsuke/commit-action@cc96d3a3fd959d05e9b79ca395eb30b835aeba24 # v0.0.7
      with:
        commit_message: "chore(deps): Update deno.lock"
      continue-on-error: true
