name: 🔒 Update Deno Lock File
description: Post update action for deno.lock

outputs:
  file_changed:
    description: If any files are modified
    value: ${{ steps.check.outputs.files != '' }}

runs:
  using: composite

  steps:
    - name: 🦕 Set up Deno
      uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4

    - name: 📦 Install dependencies
      run: deno install --frozen=false
      shell: bash

    - name: 🔍 Check changes
      id: check
      run: echo "files=$(git ls-files -mo --exclude-standard)" | tee -a "$GITHUB_OUTPUT"
      shell: bash

    - name: 📝 Commit and push changes
      if: ${{ steps.check.outputs.files != '' }}
      uses: autofix-ci/action@7a166d7532b277f34e16238930461bf77f9d7ed8 # v1.3.3
      with:
        commit-message: "chore(deps): Update deno.lock"
