name: 🔒 Update Deno Lock File
description: Post update action for deno.lock

outputs:
  file_changed:
    description: If any files are modified
    value: ${{ steps.check.outputs.files != '' }}

runs:
  using: composite

  steps:
    - name: 🦕 Setup Deno
      id: setup-deno
      uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3

    - name: 📦 Install Dependencies
      run: deno install --frozen=false
      shell: bash

    - name: 🔍 Check Changes
      id: check
      run: echo "files=$(git ls-files -mo --exclude-standard)" | tee -a "$GITHUB_OUTPUT"
      shell: bash

    - name: 📝 Commit and Push Changes
      if: ${{ steps.check.outputs.files != '' }}
      uses: suzuki-shunsuke/commit-action@cc96d3a3fd959d05e9b79ca395eb30b835aeba24 # v0.0.7
      with:
        commit_message: "chore(deps): Update deno.lock"
      continue-on-error: true
