name: 🔒 Update Deno Lock File
description: Post update action for deno.lock

inputs:
  directory:
    description: Path to the source directory
    required: false
    default: src

outputs:
  file_changed:
    description: If any files are modified
    value: ${{ steps.check.outputs.files != '' }}

runs:
  using: composite

  steps:
    - name: 🦕 Setup Deno
      uses: 5ouma/utils/setup-deno-with-cache@5d4d9189866ac7eb6c2d0534cf535f3f1f571cff # v0.1.4

    - name: 🔒 Update Lock File
      run: deno cache ${{ inputs.directory }} --frozen=false
      shell: bash

    - name: 🔍 Check Changes
      id: check
      run: echo "files=$(git ls-files -mo --exclude-standard)" | tee -a "$GITHUB_OUTPUT"
      shell: bash

    - name: 📝 Commit and Push Changes
      if: ${{ steps.check.outputs.files != '' }}
      uses: suzuki-shunsuke/commit-action@cc96d3a3fd959d05e9b79ca395eb30b835aeba24 # v0.0.7
      with:
        commit_message: "chore(deps): Update deno.lock"
      continue-on-error: true
