name: ⬆️ Update OPML in Gist

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.schedule || github.ref }}
  cancel-in-progress: true

jobs:
  update:
    name: ⬆️ Update OPML in Gist
    runs-on: Ubuntu-Slim
    environment:
      name: Gist-Update
      deployment: false
    timeout-minutes: 1

    steps:
      - name: ⬆️ Update OPML in Gist
        uses: 5ouma/opml-generator@25c45fe72197ae737bc6df2b401906cbb7083e72 # v1.1.2
        with:
          username: ${{ github.repository_owner }}
          feeds: ${{ secrets.FEEDS_GIST_ID }}
          outputs: ${{ secrets.OUTPUTS_GIST_ID }}
          token: ${{ secrets.TOKEN }}
