name: 🚸 pre-commit

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    name: 🚸 pre-commit
    runs-on: Ubuntu-Latest
    timeout-minutes: 5

    steps:
      - name: 🚸 Run pre-commit
        uses: $/pre-commit
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
